version: "3.8"
   
services:
  backend:
    image: planqk/quantum-transpiler-backend:latest
    ports:
      - "5012:5012"
  frontend:
    image: planqk/quantum-transpiler-frontend:latest
    ports:
      - "5011:80"
    depends_on:
      - backend
